org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.65-beta

mod_id=industrybase
mod_name=IndustryBase
mod_license=Mozilla Public License Version 2.0
mod_version=1.0-alpha
mod_group_id=net.industrybase
mod_authors=BinZhengStudio, vvvbbbcz, FengMing, forever_Starship
mod_description=null
