@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.industrybase.event.handler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;