modLoader="javafml"
loaderVersion="[43,)"
license="Mozilla Public License Version 2.0"
issueTrackerURL="https://github.com/BinZhengStudio/LargeProjects/issues" #optional

[[mods]]
modId="largeprojects"
version="${file.jarVersion}"
displayName="Large Projects"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/BinZhengStudio/LargeProjects/" #optional
logoFile="largeprojects.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="BinZhengStudio vvvbbbcz FengMing Nyaruko suifeng7663 essesoul" #optional
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''
'''

[[dependencies.largeprojects]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.largeprojects]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
