modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/BinZhengStudio/IndustryBase/issues"

[[mods]]
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/BinZhengStudio/IndustryBase/" 
#logoFile="${mod_id}.png"
credits="Make Minecraft great again!" 
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
