@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.industrybase.api.electric;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;