@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.industrybase.api.transmit;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;