@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.industrybase.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;