@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.industrybase.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;