name: '构建与发布'
on:
  release:
    types: [prereleased, released] # TODO 其他的事件类型待测试完善
jobs:
  release-publish:
    name: '构建与发布'
    runs-on: ubuntu-22.04
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
      - name: 配置 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 载入缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: industrybase-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys:
            industrybase-gradle-
      - name: 构建模组
        shell: bash
        run: |
          ./gradlew --max-workers=1 publish
      - name: 获取 GitHub App Token
        uses: tibdex/github-app-token@v1
        id: github-app-token
        with:
          app_id: ${{ secrets.XIANGBING_BOT_ID }}
          private_key: ${{ secrets.XIANGBING_BOT_PRIVATE_KEY }}
      - name: 检出发布仓库
        env:
          TOKEN: ${{ steps.github-app-token.outputs.token }}
        shell: bash
        run: |
          git config --global user.name 'xiangbing-bot'; git config --global user.email 'xiangbing@bzgzs.cn'
          git clone https://x-access-token:$TOKEN@github.com/BinZhengStudio/ModRelease.git --depth 1
      - name: 移动模组文件
        shell: bash
        run: |
          mv localRepo/* ModRelease/
      - name: 推送到发布仓
        shell: bash
        run: |
          cd ModRelease/
          git add .
          git commit -m "Updated at $(date -R)"
          git push
          cd ..
