name: '同步到 Gitee'

on: [push, delete]

jobs:
  mirror_to_gitee:
    name: '自动同步'
    runs-on: ubuntu-22.04
    steps:
      - name: '检出仓库'
        uses: actions/checkout@v1
      - name: '强制同步到 Gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:BinZhengStudio/IndustryBase.git
          ssh_private_key:
            ${{ secrets.GITEE_SYNC_KEY }}